### ISSUE TITLE
Sobre las mascotas

### ISSUE THREAD

**Issue by FabianGil** [compbios/quien_soy_yo-Javier-Amaya-Nieto#1]
Hola @Javier-Amaya-Nieto , 

Leí tu descripción 👍, quiero preguntarte qué opinas de los 🐶 y los 🐱 ?

**Comment by Javier-Amaya-Nieto** [comment]
En lo personal creo que tanto 🐶, como 🐱 se han convertido en miembros de las familias y en lo personal, tengo un gato llamado "nano" que alegra el hogar.
